### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Bengejd** [stormpath/stormpath-sdk-angular#58] opened 2017-01-26 22:29 UTC
When you go to run the demo through npm install, and then npm start as stated within the docs, it loads the application, but doesn't include anything on the "demo" tab of the webpage. It's just a blank page, no login or examples or anything of the sorts. Just a blank page with the header nav.

**Comment by mraible** [comment] 2017-01-26 22:33
Do you see anything in your browser console?

**Comment by Bengejd** [comment] 2017-01-26 22:36
Nope, opened up the inspect console and there are no errors. When the page initially runs. It displays the "Running stormpath" or whatever the message is, and then when it finishes, the text is gone and nothing replaces it.

Jordan

**Comment by mraible** [comment] 2017-01-26 22:38
What browser are you using and what version of node? I can fix if I can reproduce. ;)

**Comment by Bengejd** [comment] 2017-01-26 22:49
Node: 7.4.0
Browser(s): Safari 10.0.2 , Chrome: 10.12.2.

Hope that helps haha. I can send a screen cast if necessary.

**Comment by mraible** [comment] 2017-01-26 23:40
I haven't tried Node 7. Can you try with Node 6 and see if it works for you?

**Comment by mraible** [comment] 2017-01-27 01:15
I tried with Node 7.4.0 and it works fine for me. Do you have an `apiKey.properties` file in `~/.stormpath`? You need this to start the node server that it talks to.

**Comment by mraible** [comment] 2017-01-27 15:27
Closing because I'm not able to reproduce.

**Closed by mraible** 2017-01-27 15:27 UTC
